"""
VeriPath Regulatory Certificate Vault — Stage 5
Generates a KRA Certificate of Origin companion PDF that attaches the
farm's GPS coordinates (from PostGIS/farm_latitude+farm_longitude) to the
official certificate data — this is the "proof of origin" artifact.

Mirrors the lazy-import pattern used in compliance_pdf.py so a missing
reportlab install fails gracefully instead of crashing the app.
"""
from io import BytesIO
from datetime import datetime


def generate_kra_origin_pdf(vault_row: dict):
    """
    Args:
        vault_row: a row from export_regulatory_vault (dict) for a
                   KRA_CERTIFICATE_ORIGIN document, including farm_latitude
                   and farm_longitude.

    Returns:
        (bytes, error) tuple — matches the (data, error) pattern used
        in compliance_pdf.py.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                         Table, TableStyle)
        from reportlab.lib.units import mm
    except ImportError:
        return None, "reportlab not installed"

    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                 topMargin=20 * mm, bottomMargin=20 * mm)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "VPTitle", parent=styles["Heading1"],
            fontSize=16, textColor=colors.HexColor("#14201A"), spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            "VPSubtitle", parent=styles["Normal"],
            fontSize=10, textColor=colors.HexColor("#566150"), spaceAfter=16
        )

        parsed = vault_row.get("parsed_json") or {}
        lat = vault_row.get("farm_latitude")
        lon = vault_row.get("farm_longitude")

        elements = [
            Paragraph("VeriPath Africa — Certificate of Origin Verification", title_style),
            Paragraph(f"Verification Code: {vault_row.get('vp_visa_code', 'N/A')}", subtitle_style),
        ]

        data = [
            ["Field", "Value"],
            ["Document Number", vault_row.get("document_number") or "—"],
            ["Holder Name", vault_row.get("holder_name") or "—"],
            ["Origin Location", parsed.get("origin_location") or "—"],
            ["Farm GPS Coordinates",
             f"{lat}, {lon}" if lat is not None and lon is not None else "Not recorded"],
            ["Issue Date", vault_row.get("issue_date") or "—"],
            ["Expiry Date", vault_row.get("expiry_date") or "—"],
            ["Verification Status", (vault_row.get("verification_status") or "pending").upper()],
        ]

        table = Table(data, colWidths=[55 * mm, 100 * mm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#14201A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F4E8")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 16))

        footer_style = ParagraphStyle(
            "VPFooter", parent=styles["Normal"], fontSize=8,
            textColor=colors.HexColor("#999999")
        )
        elements.append(Paragraph(
            f"Generated by VeriPath Africa Ltd on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M')}. This document verifies the "
            f"origin data extracted from the uploaded KRA Certificate of Origin against "
            f"recorded farm GPS coordinates. It is a supporting compliance artifact, not "
            f"a replacement for the original government-issued certificate.",
            footer_style
        ))

        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue(), None

    except Exception as e:
        return None, f"PDF generation error: {str(e)}"
